---
title: "About Me"
---

About myself:

* Strong background in mathematics and statistics,

* experienced R, C++ and Linux user,

* Curiosity in modern technologies. 

My academic CV can be found [here](./Xiangjie Xue - Academic.pdf).

You can reach me at [Github](https://github.com/xiangjiexue),
[Email](mailto:<xxjiexxjie@gmail.com>),
[UOAwebpage](https://stat.auckland.ac.nz/~xxue017).

*** 

### Education

Ph.D., Statistics, 2020, University of Auckland (Under examination) 
[technical detail](./phdthesis.html)

B.Sc.(Hon), Statistics (First Class), 2015, University of Auckland
[technical detail](./honthesis.html)

B.Sc., Applied Mathematics and Operations Research, 2014, University of Auckland

***

### Awards and Scholarships

University of Auckland Doctoral Scholarship

Summer Research Scholarship (2013, 2015)

The $360^\circ$ Auckland Abroad Exchange Travel Awards

Senior Scholar Award in the Faculty of Science

***

### Work

Teaching Assistant in Mathematics (2013 - 2014) and Statistics (2015)

Graduate Teaching Assistant in Statistics (2016 - 2020)

Teaching courses in:

* Probability and Its Applications

* Introduction to Statistical Inference

* Statistical Computing

* Data Science Practice

***

### Publications

Xue, X. and Wang, Y. (2020). *A Non-parametric Mixture Approach to Density and Null Proportion Estimation in Large-scale Multiple Comparison Problems* [In preparation]

Xue, X. and Wang, Y. (2020). *An Empirical Bayes Approach to Large Covariance Matrix Estimation* [In preparation]

Xue, X. and Wang, Y. (2020). *On Computation of the Non-parametric Estimate of A Mixing Distribution under the Cram\'er-von Mises Distance* [In preparation]
